trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('confirm_pickup/', views.confirm_pickup, name='confirm_pickup'),
    path('date/', views.determine_day, name="determine_day")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)
    confirm_pickup = models.CharField(max_length=9)
    clocked_in = models.CharField(max_length=9)
    
    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from datetime import date
from .models import Employee
from datetime import datetime 
# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

@login_required
def index(request):
    Customer = apps.get_model('customers.Customer')
    logged_in_user = request.user
    if request.method == "POST":
       today = date.today()
       id_from_form = request.POST.get('id')
       
       complete_customer = Customer.objects.get(id=id_from_form)
       complete_customer.date_of_last_pickup = today

       complete_customer.balance += 20
       complete_customer.save()

       return HttpResponseRedirect(reverse('employees:index'))
    
    try:
        logged_in_employee = Employee.objects.get(user = logged_in_user)
        logged_in_employee_zipcode = logged_in_employee.zip_code
        today = date.today()

        days = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
        today_weekday = days[today.weekday()]

        todays_customers = Customer.objects.filter(zip_code = logged_in_employee_zipcode)\
            .filter(weekly_pickup=today_weekday)\
            .exclude(date_of_last_pickup=today)\
            .exclude(suspend_start=today)\
            .exclude(suspend_end=today)\
            .exclude(one_time_pickup=today)
        
        context = {
            'logged_in_employee': logged_in_employee,
            'today': today,
            'today_weekday': today_weekday,
            'todays_customers': todays_customers,
        }
        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))


def determine_day(request):
    today = datetime.now
    context = {
            'date': today
        }
    return render(request, 'employees/index.html', context)

def confirm_pickup(request):
    Customer = apps.get_model('customers.Customer')
    logged_in_user = request.user

    logged_in_employee = Employee.objects.get(user=logged_in_user)
    employee_zip_code = logged_in_employee.zip_code

    if request.method == "POST":
        weekday_from_form = request.POST.get('days')

        customer_match = Customer.objects.filter(zip_code=employee_zip_code)\
            .filter(weekly_pickup = weekday_from_form)\

        selected_day = weekday_from_form

        context = {
            'customer_match': customer_match,
            'logged_in_employee': logged_in_employee,
            'selected_day': selected_day
        }

        return render(request, 'employees/confirm_pickup.html', context)
    else:
        today = date.today()

        days = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
        today_weekday = days[today.weekday()]

        customer_match = Customer.objects.filter(zip_code=employee_zip_code)\
            .filter(weekly_pickup=today_weekday)

        selected_day = today_weekday

        context = {
            'customer_match': customer_match,
            'logged_in_employee': logged_in_employee,
            'selected_day': selected_day 
        }
        return render(request, 'employees/confirm_pickup.html', context)

@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_from= request.POST.get('address')
        zip_from_from= request.POST.get('zip_code')
        new_employee = Employee(name=name_from_form, user=logged_in_user, address=address_from_from, zip_code=zip_from_from)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')




@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_user = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        logged_in_user.name = name_from_form
        logged_in_user.address = address_from_form
        logged_in_user.zip_code = zip_from_form
        logged_in_user.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_user
        }
        return render(request, 'employees/edit_profile.html', context)

trash_collector/employees/templates/employees/confirm_pickup.html
{% extends 'base.html' %}

{% block title %} Employee Home {% endblock %}

{%block header %} Confirm Pick ups {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
    <br />
    To view customer schedule, choose the day below (default is today):
    <br />

 <form action="{% url 'employees:confirm_pickup' %}" method="POST">
     {% csrf_token %}

     <label>Day of the Week</label>

     <select name="days" id="days">
     <option value="monday">Monday</option>
     <option value="tuesday">tuesday</option>
     <option value="wednesday">wednesday</option>
     <option value="thursday">thursday</option>
     <option value="friday">friday</option>
     <option value="saturday">saturday</option>
     <option value="sunday">sunday</option>
     </select>
     <input type="submit" value="Search">
 </form> 
 <br />

 Pickups for Zip Code below: {{logged_in_employee.zip_code}} for {{selected_day}}<br />
 {% for customer in customer_match %}
    <br />
    Name: <input type="name" name="name" id="name" value="{{customer.name}}" readonly>
    Address: <input type="address" name="address" id="address" value="{{customer.address}}" readonly>
    <br />
{% endfor %}


{% else %}
 <p>You are at the employee index, Please log in</p>
 <a href="{% url 'login' %}">Log in</a>
 <a href="{% url 'accounts:register' %}">Sign Up</a>
 {% endif %}
 {% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Save">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'base.html' %}

{% block navbar %}

{% endblock %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />
<form action="{% url 'employees:edit_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name" >
    <br />
    <br />
    Address: <input type="text" name="address" id="address" >
    <br />
    <br />
    Zip Code: <input type="text" name="zip_code" id="zip_code">
    <br />
    <br />
    <input type="submit" class="btn btn-info"value="Submit">
</form>
{% endblock %}

trash_collector/employees/templates/employees/employees_base.html
{% extends 'base.html' %}
    
{% block navbar %}
    <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
    <a class="nav-item nav-link" href="{% url 'employees:index' %}">Index</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
    <a class="nav-item nav-link" href="{% url 'employees:confirm_pickup' %}">Confirm Pickup</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees/employees_base.html' %}
<head>
  <title>Garbage Pick-up</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
{% block title %} Employee Home {% endblock %}

{% block header %} Employee Portal {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  Hello {{ user.username }}!<br />
  Address: {{ logged_in_employee.address }}<br />
  ZipCode: {{ logged_in_employee.zip_code}}<br />
  
  <br />
  <br />
  <h3>Customers needing pick up in current Zip Code:</h3>
  {% for customer in todays_customers %}
  <form action="{% url 'employees:index' %}" method="post">
    {% csrf_token %}
      ID: <input type="id" name="id" id="id" value="{{customer.id}}" readonly>
      Name: <input type="name" name="name" id="name" value="{{customer.name}}" readonly>
      Address: <input type="address" name="address" id="address" value="{{customer.address}}" readonly>
      <input type="submit" class="btn btn-danger" id='script' name='Button' value=" Job Complete " onclick="index(complete_customer.balance)">
      <br />
      <br />
  </form>
  {% endfor %}
  <br />
  <br />
  
  <img src="trash man.jpg" class="img-thumbnail" alt="Trash Man">

  <br />
  Today's date is: {{ today }}<br />
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}